# Generated by Django 5.2.9 on 2025-12-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='ocupacao',
        ),
    ]
