# Generated by Django 5.2.9 on 2025-12-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_agendamento_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='titulo',
            field=models.CharField(default=3, max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
