# Generated by Django 5.2.8 on 2025-11-28 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_author_delete_resultadocalc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCalculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calculo', models.CharField(choices=[('imc', 'IMC'), ('glicose', 'Glicose'), ('agua', 'Hidratação Diária'), ('pressao', 'Pressão Arterial')], max_length=20)),
                ('resultado', models.JSONField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado da Calculadora',
                'verbose_name_plural': 'Resultados da Calculadora',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
