# Generated by Django 5.2.8 on 2025-12-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_resultadocalculadora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='endereco',
        ),
    ]
